title: "Building Websites in Github"
description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "team@carpentries.org"
twitter: "http://twitter.com/DanTBrady"
team_members: [
    {name: "Jane Smith", role: "maintainer", start_date: "2018-03-15"},
    {name: "Albert Hamilton", role: "editor", start_date: "2017-12-01"},
    {name: "Tom Cat", role: "project lead", start_date: "2020-10-01"},
    {name: "Alice Dauncey", role: "developer", start_date: "2020-09-15"}
]

alumni: [
    {name: "Sarah Becker", role: "alumni", start_date: "2016-02-01"},
]

collections:
    - posts:
        output: true
